void frameInit(int frameNumber){
  if(frameNumber == FOOD){
    GLOBAL_SUN_DEG =90;
    GLOBAL_RAIN_POSITION = -50;
    GLOBAL_CLOUD1_POSITION = 800;
    GLOBAL_CROP_SCALE = 0.4;
    GLOBAL_DISPLAY_RAIN = 0;
    GLOBAL_BACKGROUND_RED = 0.4,GLOBAL_BACKGROUND_GREEN = 0.4,GLOBAL_BACKGROUND_BLUE = 0.4;
    GLOBAL_BACKGROUND_LOWER_RED = 0.5,GLOBAL_BACKGROUND_LOWER_GREEN = 0.38,GLOBAL_BACKGROUND_LOWER_BLUE = 0.13;
  }else if(frameNumber == WATER){
    GLOBAL_SUN_DEG = 300;
    GLOBAL_RAIN_POSITION = -50;
    GLOBAL_CLOUD1_POSITION = 800;
    GLOBAL_CLOUD2_POSITION = -800;
    GLOBAL_BACKGROUND_RED = 0.4,GLOBAL_BACKGROUND_GREEN = 0.4,GLOBAL_BACKGROUND_BLUE = 0.4;
    GLOBAL_BACKGROUND_LOWER_RED = 0.5,GLOBAL_BACKGROUND_LOWER_GREEN = 0.38,GLOBAL_BACKGROUND_LOWER_BLUE = 0.13;
  }else if(frameNumber == SHELTER){
    GLOBAL_SUN_DEG = 60;
    GLOBAL_RAIN_POSITION = -50;
    GLOBAL_CLOUD1_POSITION = 1000;
    GLOBAL_DISPLAY_RAIN = 0;
    GLOBAL_BACKGROUND_RED = 0.95,GLOBAL_BACKGROUND_GREEN = 0.75,GLOBAL_BACKGROUND_BLUE = 0.45;
    GLOBAL_BACKGROUND_LOWER_RED = 0.6,GLOBAL_BACKGROUND_LOWER_GREEN = 0.9,GLOBAL_BACKGROUND_LOWER_BLUE = 0.6;
  }else if(frameNumber == POWER){
    GLOBAL_SUN_DEG = 60;
    GLOBAL_SMOKE_SCALE = 0.4;
    GLOBAL_SMOKE_Y_POS = 100;
    GLOBAL_BACKGROUND_RED = 0.95,GLOBAL_BACKGROUND_GREEN = 0.75,GLOBAL_BACKGROUND_BLUE = 0.45;
    GLOBAL_BACKGROUND_LOWER_RED = 0.5,GLOBAL_BACKGROUND_LOWER_GREEN = 0.38,GLOBAL_BACKGROUND_LOWER_BLUE = 0.13;
  }else if(frameNumber == EDUCATION){
    GLOBAL_SUN_DEG = 60;
    GLOBAL_CLOUD1_POSITION = 1200;
    GLOBAL_CLOUD2_POSITION = -1200;
    GLOBAL_SCHOOL_BUS_X_POS = 1200;
    GLOBAL_BACKGROUND_RED = 0.95,GLOBAL_BACKGROUND_GREEN = 0.75,GLOBAL_BACKGROUND_BLUE = 0.45;
    GLOBAL_BACKGROUND_LOWER_RED = 0.6,GLOBAL_BACKGROUND_LOWER_GREEN = 0.9,GLOBAL_BACKGROUND_LOWER_BLUE = 0.6;
  }else if(frameNumber == HEALTHCARE){
    GLOBAL_SUN_DEG = 300;
    GLOBAL_AMBULANCE_X_POS = -1200;
    GLOBAL_BACKGROUND_RED = 0.4,GLOBAL_BACKGROUND_GREEN = 0.4,GLOBAL_BACKGROUND_BLUE = 0.4;
    GLOBAL_BACKGROUND_LOWER_RED = 0.5,GLOBAL_BACKGROUND_LOWER_GREEN = 0.38,GLOBAL_BACKGROUND_LOWER_BLUE = 0.13;
  }
}

//frame1
int show = 0;
void writeText(int x,int y,char str[],float r=0,float g=0,float b=0,float scale=3.0){
  glColor3f(r,g,b);
  glPushMatrix();
  glTranslatef(x,y,1);
  glScalef(1/scale,1/scale,1);
  for(p=str;*p;p++){
    glutStrokeCharacter(GLUT_STROKE_ROMAN,*p);
  }
  glPopMatrix();
}

void writeBitmapText(int x,int y,char str[],float r=0,float g=0,float b=0){
  glColor3f(r,g,b);
  glPushMatrix();
  glRasterPos2i(x-100,y);
  for(i=0;i<strlen(str);i++){
    glutBitmapCharacter(GLUT_BITMAP_TIMES_ROMAN_24,str[i]);
  }
  glPopMatrix();
}
