int WIDTH_OF_VIEWPORT = 1000;
int HEIGHT_OF_VIEWPORT = 600;

void init(){
  glClearColor(1.0,1.0,1.0,1.0);
  glOrtho(-WIDTH_OF_VIEWPORT,WIDTH_OF_VIEWPORT,-HEIGHT_OF_VIEWPORT,HEIGHT_OF_VIEWPORT,-1,1);
}
